name: Build CashBook Pro
on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: Install MinGW
        run: choco install mingw -y
        shell: pwsh
      - name: Compile
        run: g++ -static -o CashBookPro.exe Main.cpp -lgdi32 -lcomctl32 -luser32 -lkernel32 -mwindows -std=c++11 -O2 -s
        shell: cmd
      - uses: actions/upload-artifact@v4
        with:
          name: CashBookPro
          path: CashBookPro.exe
